import { topic, lesson, lines } from './curated-course-authoring.mjs';

topic('time', 'Time, dates, and plans', 'Tell the time, talk about dates, and arrange a meeting.');
lesson('clock', 'The time: one to five', [79,438,85,86,87,88,89], '今 は 何時 です か', '何時 asks the time. Put a number before 時（じ）. Start with one to five. Four o’clock is よじ. 今は means “as for now”; you can leave it out when the time being asked about is clear.', [
 ['79 は 438 です か','What time is it now?'],['438 です か','What time is it?'],
 ...lines([[85,'one'],[86,'two'],[87,'three'],['88~四~よ','four'],[89,'five']], [['79 は $ 時 です','It is $ o’clock now.'],['$ 時 です か','Is it $ o’clock?']])]);
lesson('clock-later', 'The time: six to ten', [90,91,92,93,94], '今 は 六 時 です', 'Keep the same time pattern and add six to ten. Seven o’clock is しちじ and nine o’clock is くじ. The second group asks about the same hours, so listen for the final か.',
 lines([[90,'six'],[91,'seven'],[92,'eight'],['93~九~く','nine'],[94,'ten']], [['79 は $ 時 です','It is $ o’clock now.'],['$ 時 です か','Is it $ o’clock?']]));
lesson('minutes', 'Minutes and half past', [243,244,242,622,320,321], '時 + 分 / 時半 / 午前・午後', '分 counts minutes, with changes such as いっぷん and ごふん. 半 after an hour means half past. 午前 is a.m. and 午後 is p.m. ちょうど means exactly; 時間 is time or duration.', [
 ['79 は 87 時 89 243~分~ふん です','It is five past three now.'],['79 は 87 時 94~十~じゅっ 243~分~ぷん です','It is ten past three now.'],['79 は 87 時 244 です','It is half past three now.'],['79 は 89 時 244 です','It is half past five now.'],['622 87 時 です','It is exactly three o’clock.'],['622 89 時 です','It is exactly five o’clock.'],['321 93~九~く 時 です','It is nine a.m.'],['321 91 時 です','It is seven a.m.'],['320 87 時 です','It is three p.m.'],['320 89 時 です','It is five p.m.'],['242 は 87 時 から 89 時 まで です','The time is from three to five o’clock.'],['242 は 91 時 から 93~九~く 時 まで です','The time is from seven to nine o’clock.']]);
lesson('days', 'Today, tomorrow, yesterday', [76,77,78,84,328,327], 'Nはいつですか / です・でした', 'いつ asks when. 今日, 明日 and 昨日 are relative days and usually do not need に. でした is the past of です. 休み can mean a day off; 誕生日 means birthday.', [
 ['76 は 328 です','Today is a day off.'],['77 は 328 です','Tomorrow is a day off.'],['78 は 328 でした','Yesterday was a day off.'],['327 は 84 です か','When is your birthday?'],['328 は 84 です か','When is your day off?'],['327 は 76 です','My birthday is today.'],['327 は 77 です','My birthday is tomorrow.'],['327 は 78 でした','My birthday was yesterday.']]);
lesson('weekdays', 'Days of the week', [323,324,445,450,441,448,451], '曜日 / NからNまで', 'The seven day names end in 曜日. から means from and まで means until. A named day can be followed by に before an action; these cards first establish the day names.', [
 ...lines([[323,'Monday'],[324,'Tuesday'],[445,'Wednesday'],[450,'Thursday'],[441,'Friday'],[448,'Saturday'],[451,'Sunday']], [['76 は $ です','Today is $.'],['328 は $ です','My day off is $.']]),
 ['323 から 441 まで です','It is from Monday to Friday.'],['448 から 451 まで 328 です','I am off from Saturday through Sunday.']]);
lesson('weeks', 'Weeks and weekends', [442,443,452,249,714,715,478,482], '今週・先週・来週 / 毎週', '今週 is this week, 先週 last week, and 来週 next week. 毎週 means every week. 週末 is the weekend; 平日 a weekday; 休日 a day off; 祝日 a public holiday.', [
 ['442 は 328 です','I am off this week.'],['443 は 328 でした','I was off last week.'],['452 は 328 です','I am off next week.'],['442 の 714 です','It is this weekend.'],['443 の 714 でした','It was last weekend.'],['452 の 714 です','It is next weekend.'],['249 451 は 328 です','Every Sunday is a day off.'],['249 448 は 328 です','Every Saturday is a day off.'],['76 は 715 です','Today is a day off.'],['77 は 715 です','Tomorrow is a day off.'],['76 は 478 です','Today is a public holiday.'],['77 は 478 です','Tomorrow is a public holiday.'],['76 は 482 です','Today is a weekday.'],['77 は 482 です','Tomorrow is a weekday.']]);
lesson('dates', 'Dates: the first to the fifth', [628,631,632,633,634,635], '何日 / ついたち・ふつか・みっか・よっか・いつか', '何日（なんにち）asks the date here. Learn these five day names as whole words. The first day of a month is ついたち, not いちにち. Reuse the same date names when saying when a birthday falls.', [
 ['76 は 628 です か','What is today’s date?'],['327 は 628 です か','What day of the month is your birthday?'],
 ...lines([[631,'first'],[632,'second'],[633,'third'],[634,'fourth'],[635,'fifth']], [['76 は $ です','Today is the $.'],['327 は $ です','My birthday is on the $.']])]);
lesson('dates-later', 'More dates with special readings', [636,637,638,639,640,641], 'むいか・なのか・ようか・ここのか・とおか・はつか', 'Continue with the sixth through the tenth. The twentieth has its own name, はつか. These are calendar dates; keep their readings together rather than combining a number with にち.',
 lines([[636,'sixth'],[637,'seventh'],[638,'eighth'],[639,'ninth'],[640,'tenth'],[641,'twentieth']], [['76 は $ です','Today is the $.'],['327 は $ です','My birthday is on the $.']]));
lesson('one-day', 'One day off', [752], '一日（いちにち） / 一日の休み', '一日（いちにち）means a duration of one day, or all day before an action or state. 一日の休み is one day off. A duration can come before the verb without に. Keep this separate from １日（ついたち）, the first day of a calendar month.', [
 ['328 は 752 です','I have one day off.'],
 ['443 の 328 は 752 でした','I had one day off last week.'],
 ['77 は 752 51 に 50~います~います','I will be at home all day tomorrow.'],
 ['752 の 328 が 49~あります~あります','I have a day off.'],
]);
lesson('months', 'Months', [246,247,515,516,629,464], '今月 は 一 月 です', 'Calendar months use 月（がつ）, not the noun 月（つき）for the moon. April is しがつ, July is しちがつ, and September is くがつ. 何月 asks which month. 毎月 means every month.', [
 ['246 は 85 月 です','This month is January.'],['247 は 86 月 です','Next month is February.'],['515 は 87 月 でした','Last month was March.'],['246 は 88 月 です','This month is April.'],['247 は 89 月 です','Next month is May.'],['515 は 90 月 でした','Last month was June.'],['327 は 629 です か','What month is your birthday?'],['79 は 629 です か','What month is it now?'],['516 631 は 328 です','The first day of every month is a day off.'],['516 635 は 328 です','The fifth day of every month is a day off.'],['23 は 464 です','This is a calendar.'],['1 の 464 です','This is my calendar.']]);
lesson('years', 'Years', [245,508,509,248,517,630], '今年・去年・来年 / 年（ねん）', '年 as a general noun can be read とし; after numbers it is usually ねん. 今年 is this year, 去年 last year, and 来年 next year. 毎年 means every year. 何年 can ask a year or a duration.', [
 ['508 の 327 は 451 です','My birthday is on Sunday this year.'],['509 の 327 は 448 でした','My birthday was on Saturday last year.'],['248 の 327 は 323 です','My birthday is on Monday next year.'],['508 の 327 は 328 です','I have my birthday off this year.'],['509 の 327 は 328 でした','I had my birthday off last year.'],['248 の 327 は 328 です','I have my birthday off next year.'],['517 327 は 328 です','I take my birthday off every year.'],['517 85 月 は 258 です','It is cold every January.'],['79 は 630 です か','What year is it now?'],['630 です か','How many years is it?'],['85 245~年~ねん です','It is one year.'],['87 245~年~ねん です','It is three years.']]);
lesson('meeting', 'Making a plan', [114,113,711,712,713,513,507,66], '明日 友達 に 会います', '会います uses に for the person you meet; 待ちます uses を for the person you wait for. 約束 can be an arrangement or promise. 用事があります means you have something you need to do, and 都合 refers to availability or circumstances.', [
 ['77 71 に 114~会います~あいます','I will meet my friend tomorrow.'],['451 に 71 に 114~会います~あいます','I meet my friend on Sunday.'],['71 を 113~待ちます~まちます','I wait for my friend.'],['87 時 まで 113~待ちます~まちます','I wait until three o’clock.'],['711 は 77 です','The arrangement is for tomorrow.'],['711 は 87 時 です','The appointment is at three o’clock.'],['76 は 712 が 49~あります~あります','I have something to do today.'],['77 は 712 が 49~あります~あります','I have something to do tomorrow.'],['713 は 507 です か','How is your availability?'],['77 の 713 は 507 です か','How is tomorrow for you?'],['77 は 713 が 66 です','Tomorrow works for me.'],['451 は 713 が 66 です','Sunday works for me.'],['513 の 711 は 77 です','The next appointment is tomorrow.'],['513 の 328 は 451 です','My next day off is Sunday.']]);
