import { topic, lesson, lines } from './curated-course-authoring.mjs';

topic('home', 'Home and belongings', 'Describe your home, find things, and manage everyday household tasks.');
lesson('rooms', 'A place to live', [51,52,54], '場所にNがあります', 'あります says that a thing exists. Put its location before に, and the thing before が. For people and animals Japanese uses a different verb, います. は marks the thing you want to locate. それ points near the listener and あれ farther from both of you. あなたの asks about the listener’s belongings; use their name instead when it is known.', [
 ['52 に 54 が 49~あります~あります','There is a desk in the room.'],['52 に 53 が 49~あります~あります','There is a chair in the room.'],['54 は 52 に 49~あります~あります','The desk is in the room.'],['53 は 52 に 49~あります~あります','The chair is in the room.'],['1 の 51 です','This is my house.'],['51 は 67 です','The house is big.'],['52 は 68 です','The room is small.'],['54 は 69 です','The desk is new.'],['24 は 295 の 32 です か','Is that your book?'],['25 は 295 の 136 です か','Is that your car over there?']]);
lesson('housing', 'Different homes', [309,312,315,107], '場所に住んでいます / NのN', '住んでいます describes where you live now. A マンション is an apartment or condominium building, not an English mansion. うち often means your own home; 家 is the general word for house.', [
 ['309 に 107~住んでいます~すんでいます','I live in an apartment.'],['312 に 107~住んでいます~すんでいます','I live in a condominium.'],['51 に 107~住んでいます~すんでいます','I live in a house.'],['1 の 315 です','This is my home.'],['315 は 68 です','My home is small.'],['309 の 52 は 69 です','The room in the apartment is new.'],['312 の 52 は 67 です','The room in the condominium is big.']]);
lesson('furniture', 'Furniture', [310,313,415,428,425], '場所にNがあります / Nは…です', 'Name the furniture in a room with があります. In a question, は can focus on the item you are looking for. Japanese does not distinguish “a shelf” and “shelves” in the noun itself.', [...lines([[310,'a bed'],[313,'a table'],[415,'a sofa'],[428,'a shelf'],[425,'a box']], [['52 に $ が 49~あります~あります','There is $ in the room.'],['$ は 52 に 49~あります~あります か','Is there $ in the room?'],['23 は $ です','This is $.']]),['24 は 295 の 310 です か','Is that your bed?'],['25 は 295 の 313 です か','Is that your table over there?']]);
lesson('locations', 'Where things are', [228,229,230,231,232,233,236], 'Nの位置にあります', 'A position word follows the reference object with の: 机の上 is “on top of the desk”. Use に with あります to locate a thing. 前 and 後ろ describe front and back.', [
 ...lines([[228,'on'],[229,'under']], [['32 は 54 の $ に 49~あります~あります','The book is $ the desk.'],['425 は 54 の $ に 49~あります~あります','The box is $ the desk.']]),
 ['32 は 425 の 230 に 49~あります~あります','The book is inside the box.'],['53 は 52 の 230 に 49~あります~あります','The chair is inside the room.'],['136 は 51 の 231 に 49~あります~あります','The car is outside the house.'],['425 は 52 の 231 に 49~あります~あります','The box is outside the room.'],
 ...lines([[232,'in front of'],[233,'behind'],[236,'next to']], [['53 は 54 の $ に 49~あります~あります','The chair is $ the desk.'],['425 は 310 の $ に 49~あります~あります','The box is $ the bed.']])]);
lesson('more-locations', 'Left, right, and between', [234,235,237,430,648,649,650], 'Nの右 / NとNの間', '右 and 左 mean right and left. 間 uses two reference points joined with と. 近く is nearby; 横 is beside; 向こう is on the other side; 奥 is farther inside.', [
 ...lines([[234,'to the right of'],[235,'to the left of'],[237,'near'],[430,'beside'],[648,'beyond']], [['53 は 54 の $ に 49~あります~あります','The chair is $ the desk.'],['425 は 310 の $ に 49~あります~あります','The box is $ the bed.']]),
 ['53 は 54 と 310 の 649 に 49~あります~あります','The chair is between the desk and the bed.'],['425 は 54 と 310 の 649 に 49~あります~あります','The box is between the desk and the bed.'],['54 は 52 の 650 に 49~あります~あります','The desk is at the back of the room.'],['310 は 52 の 650 に 49~あります~あります','The bed is at the back of the room.']]);
lesson('parts', 'Parts of a home', [162,163,417,422,424,426], 'Nは…です / 場所にあります', 'A noun can be the topic of a description with は. 窓 is a window, ドア a door, and 玄関 the entrance area where you take off shoes. お風呂 can refer to the bath or bathing area.', [
 ...lines([[162,'window'],[163,'door']], [['$ は 67 です','The $ is big.'],['52 に $ が 49~あります~あります','There is a $ in the room.']]),
 ...lines([[417,'entryway'],[422,'bath'],[424,'kitchen'],[426,'garden']], [['$ は 68 です','The $ is small.'],['1 の 51 の $ です','This is the $ at my home.']])]);
lesson('surfaces', 'Inside and outside the house', [552,553,554,410,413,414,418], 'い-adjectives / Nは…です', '広い means spacious and 狭い means cramped or narrow. 明るい and 暗い describe brightness. Walls, floors, and roofs are parts of a home, not separate rooms.', [
 ['52 は 410 です','The room is bright.'],['424 は 410 です','The kitchen is bright.'],['52 は 413 です','The room is dark.'],['417 は 413 です','The entryway is dark.'],['52 は 414 です','The room is cramped.'],['424 は 414 です','The kitchen is cramped.'],['52 は 418 です','The room is spacious.'],['426 は 418 です','The garden is spacious.'],
 ...lines([[552,'wall'],[553,'floor'],[554,'roof']], [['51 の $ は 70 です','The house’s $ is old.'],['51 の $ は 69 です','The house’s $ is new.']])]);
lesson('appliances', 'Appliances', [311,314,555,556,557,344,600,654], 'な-adjective + です', '便利 and 不便 are な-adjectives. At the end of a sentence, use 便利です; な is used only before a noun. エアコン is air conditioning, while エレベーター is an elevator.', [
 ...lines([[311,'air conditioner'],[314,'television'],[555,'refrigerator'],[556,'washing machine'],[557,'vacuum cleaner']], [['$ は 69 です','The $ is new.'],['$ は 344 です','The $ is useful.']]),
 ['312 に 654 が 49~あります~あります','There is an elevator in the condominium building.'],['654 は 344 です','The elevator is convenient.'],['51 は 600 です','The house is inconvenient.'],['424 は 600 です','The kitchen is inconvenient to use.']]);
lesson('everyday-items', 'Everyday belongings', [164,429,427,558,559,560], 'Nの上にあります / Nは…です', 'Use the same location pattern for smaller belongings. 布団 is Japanese bedding; 毛布 is a blanket. 写真 is a photograph, and 時計 can be a clock or watch.', [
 ...lines([[164,'key'],[429,'clock'],[427,'photograph'],[560,'mirror']], [['$ は 54 の 228 に 49~あります~あります','The $ is on the desk.'],['$ は 69 です','The $ is new.']]),
 ['558 は 52 に 49~あります~あります','The futon is in the room.'],['558 は 69 です','The futon is new.'],['559 は 310 の 228 に 49~あります~あります','The blanket is on the bed.'],['559 は 69 です','The blanket is new.']]);
lesson('open-close', 'Opening and closing', [192,193,578,579], 'を + transitive verb / が + intransitive verb', '開けます and 閉めます describe what someone does to a door or window, using を. 開きます and 閉まります describe the door or window itself, using が. These are different dictionary words, not interchangeable forms.', [
 ...lines([[162,'window'],[163,'door']], [['$ を 192~開けます~あけます','I open the $.'],['$ を 193~閉めます~しめます','I close the $.'],['$ が 578~開きます~あきます','The $ opens.'],['$ が 579~閉まります~しまります','The $ closes.']])]);
lesson('moving-things', 'Putting things away', [191,202,203,589], 'Nを場所に入れます / Nを場所から出します', 'を marks the object you move. に marks where you put it; から marks where you take it from. 置きます means put or place, while 捨てます means throw away.', [
 ['32 を 425 に 203~入れます~いれます','I put the book in the box.'],['427 を 425 に 203~入れます~いれます','I put the photograph in the box.'],['32 を 425 から 191~出します~だします','I take the book out of the box.'],['427 を 425 から 191~出します~だします','I take the photograph out of the box.'],['32 を 54 に 202~置きます~おきます','I put the book on the desk.'],['425 を 54 に 202~置きます~おきます','I put the box on the desk.'],['70 425 を 589~捨てます~すてます','I throw away the old box.'],['70 32 を 589~捨てます~すてます','I throw away the old book.']]);
lesson('household-actions', 'Switching on and off', [165,204,593,194,195], '電気 を つけます', 'つけます means switch on in these electrical contexts; 消します means switch off. 座ります uses に for the place you sit. 立ちます means stand up or stand; the location can also use に.', [
 ['165 を 593~つけます~つけます','I turn on the light.'],['314 を 593~つけます~つけます','I turn on the television.'],['311 を 593~つけます~つけます','I turn on the air conditioner.'],['165 を 204~消します~けします','I turn off the light.'],['314 を 204~消します~けします','I turn off the television.'],['311 を 204~消します~けします','I turn off the air conditioner.'],['53 に 195~座ります~すわります','I sit on the chair.'],['415 に 195~座ります~すわります','I sit on the sofa.'],['163 の 232 に 194~立ちます~たちます','I stand in front of the door.'],['162 の 232 に 194~立ちます~たちます','I stand in front of the window.']]);
lesson('washing', 'Washing and cleaning', [561,562,563,605,196,505,506], '道具でNを洗います / verbal noun + します', 'で marks a tool or material: 石鹸で means “with soap”. 洗濯します means do the laundry; 掃除します means clean. 汚い is an い-adjective describing something dirty.', [
 ['561 で 563 を 196~洗います~あらいます','I wash the towel with soap.'],['561 で 559 を 196~洗います~あらいます','I wash the blanket with soap.'],['562 を 196~洗います~あらいます','I wash the toothbrush.'],['562 は 605 です','The toothbrush is dirty.'],['563 は 605 です','The towel is dirty.'],['563 を 196~洗います~あらいます','I wash the towel.'],['51 で 505~洗濯します~せんたくします','I do laundry at home.'],['52 で 505~洗濯します~せんたくします','I do laundry in the room.'],['52 を 506~掃除します~そうじします','I clean the room.'],['424 を 506~掃除します~そうじします','I clean the kitchen.']]);
