import { topic, lesson, lines } from './curated-course-authoring.mjs';

topic('routine', 'Daily life and work', 'Describe everyday routines, work, and how often you do things.');
lesson('day-night', 'Morning and night', [80,81,82,83,119,120], '朝 起きます', '朝, 昼 and 夜 are morning, midday and night. These broad time words often stand without に. 起きます means get up; 寝ます means go to bed or sleep. 毎日 means every day.', [
 ['80 120~起きます~おきます','I get up in the morning.'],['81 120~起きます~おきます','I get up at midday.'],['82 119~寝ます~ねます','I go to bed at night.'],['81 119~寝ます~ねます','I sleep during the day.'],['83 80 120~起きます~おきます','I get up every morning.'],['83 82 119~寝ます~ねます','I go to bed every night.']]);
lesson('work', 'Working', [106,141,142,501], '場所で働きます / Nの仕事', '働きます means work, and で marks the workplace. 仕事 is a job or work; 会社 a company. アルバイト means a part-time job. A Japanese noun can stand for an activity in a simple schedule statement.', [
 ['142 で 106~働きます~はたらきます','I work at a company.'],['82 106~働きます~はたらきます','I work at night.'],['83 106~働きます~はたらきます','I work every day.'],['1 の 141 です','This is my job.'],['80 は 141 です','I work in the morning.'],['142 の 141 です','It is company work.'],['82 は 501 です','I have my part-time job at night.'],['501 で 106~働きます~はたらきます','I work part-time.']]);
lesson('start-finish', 'Starting and finishing', [198,199,583,584], 'Nを始めます / Nが始まります / Nに遅れます', '始めます describes a person starting something, with を. 始まります describes something beginning, with が. 終わります describes an event ending. 遅れます uses に for the event you are late for.', [
 ['141 を 198~始めます~はじめます','I start work.'],['501 を 198~始めます~はじめます','I start a part-time job.'],['141 が 583~始まります~はじまります','Work begins.'],['501 が 583~始まります~はじまります','My part-time shift begins.'],['141 が 199~終わります~おわります','Work ends.'],['501 が 199~終わります~おわります','My part-time shift ends.'],['141 に 584~遅れます~おくれます','I am late for work.'],['501 に 584~遅れます~おくれます','I am late for my part-time job.']]);
lesson('busy-days', 'Busy and quiet routines', [431,432,302,348,377,433], 'い-adjectives / な-adjectives', '早い means early in these time contexts; 遅い means late. 忙しい is busy. 楽 describes something easy or comfortable, while 大変 describes something demanding. 生活 means everyday life or one’s way of life. Change the final い to く when describing how an action happens: 早く起きます, get up early.', [
 ['80 は 431 です','I am busy in the morning.'],['82 は 431 です','I am busy at night.'],['141 は 302~早く~はやく 199~終わります~おわります','Work ends early.'],['141 は 432~遅く~おそく 199~終わります~おわります','Work ends late.'],['80 302~早く~はやく 120~起きます~おきます','I get up early in the morning.'],['82 432~遅く~おそく 119~寝ます~ねます','I go to bed late at night.'],['141 は 348 です','The work is easy.'],['433 は 348 です','Life is comfortable.'],['141 は 377 です','The work is hard.'],['433 は 377 です','Life is hard.']]);
lesson('frequency', 'How often?', [398,405,463,224], '夜 いつも 働きます', 'いつも means always; よく often; 時々 sometimes. Place these before the verb. すぐ means right away. It describes timing rather than frequency.', [
 ...lines([[398,'always'],[405,'often'],[463,'sometimes']], [['82 $ 106~働きます~はたらきます','I $ work at night.'],['81 $ 119~寝ます~ねます','I $ sleep during the day.']]),
 ['224 141 を 198~始めます~はじめます','I start work right away.'],['224 119~寝ます~ねます','I go to bed right away.']]);
lesson('shower-shopping', 'Everyday activities', [197,434,440,200], 'シャワーを浴びます / Nをします / Nができます', '浴びます is used for taking a shower. します is the polite form of する, “do”. 買い物をします means go shopping. できます means can do; in these examples it takes a noun with が.', [
 ['434 を 197~浴びます~あびます','I take a shower.'],['80 434 を 197~浴びます~あびます','I take a shower in the morning.'],['82 434 を 197~浴びます~あびます','I take a shower at night.'],['1 は 440~買い物します~かいものします','I do the shopping.'],['80 440~買い物します~かいものします','I go shopping in the morning.'],['440 が 200~できます~できます','I can do the shopping.'],['141 が 200~できます~できます','I can do the work.']]);
lesson('day-parts', 'Parts of the day', [518,519,520,523,524,525], '時の表現 + Vます / Vました', '今朝 means this morning and 今晩 means tonight. 午前中 is during the morning, 夕方 early evening, 夜中 the middle of the night, and 晩 evening. ました is the polite past.', [
 ...lines([[518,'in the evening'],[519,'tonight'],[523,'during the morning'],[524,'in the early evening'],[525,'in the middle of the night']], [['$ 106~働きます~はたらきます','I work $.'],['$ 434 を 197~浴びます~あびます','I take a shower $.']]),
 ['520 434 を 197~浴びました~あびました','I took a shower this morning.'],['520 106~働きました~はたらきました','I worked this morning.']]);
lesson('already-not-yet', 'Already or not yet?', [387,388], 'もうVました / まだVていません', 'もう with the past asks or says that something has already happened. まだ with a negative describes “not yet”. The exact negative forms here are していません and 浴びていません.', [
 ['388 440~買い物しました~かいものしました','I have already done the shopping.'],['388 434 を 197~浴びました~あびました','I have already taken a shower.'],['388 440~買い物しました~かいものしました か','Have you done the shopping yet?'],['387 440~買い物していません~かいものしていません','I have not done the shopping yet.'],['387 434 を 197~浴びていません~あびていません','I have not taken a shower yet.'],['387 106~働いています~はたらいています','I am still working.']]);

topic('leisure', 'Hobbies and free time', 'Talk about interests, enjoy entertainment, and try an activity.');
lesson('interests', 'What you enjoy', [99,217,336,333,39,40], 'Nが好きです / Nが嫌いです', '好き and 嫌い behave as な-adjectives and use が for the thing liked or disliked. 趣味 is a hobby. 聞きます means listen in the music context; 見ます means look at or watch.', [
 ['333 が 99 です','I like music.'],['333 が 217 です','I dislike music.'],['333 を 40~聞きます~ききます','I listen to music.'],['71 も 333 を 40~聞きます~ききます','My friend also listens to music.'],['314 を 39~見ます~みます','I watch television.'],['71 も 314 を 39~見ます~みます','My friend also watches television.'],['1 の 336 は 333 です','My hobby is music.'],['336 は 333 です か','Is music your hobby?'],['333 が 99 です か','Do you like music?'],['333 が 217 です か','Do you dislike music?']]);
lesson('screen', 'Movies and animation', [329,330,332,485,511,601], 'Nは面白いです / Nが好きです', '面白い can mean interesting or funny. 楽しい means enjoyable; つまらない means boring. 漫画 is manga or comics, while アニメ is animation. Use 見ます for watching a film and 読みます for reading manga. Both actions take を.', [
 ...lines([[329,'anime'],[330,'movies'],[332,'manga']], [['$ が 99 です','I like $.']]),['329 を 39~見ます~みます','I watch anime.'],['330 を 39~見ます~みます','I watch a movie.'],['332 を 42~読みます~よみます','I read manga.'],
 ['330 は 485 です','The movie is interesting.'],['332 は 485 です','The manga is interesting.'],['330 は 601 です','The movie is boring.'],['332 は 601 です','The manga is boring.'],['329 は 511 です','Anime is enjoyable.'],['333 は 511 です','Music is enjoyable.']]);
lesson('music', 'Music and singing', [331,334,342,454,502,325], 'Nを歌います / Nが好きです', '歌います means sing and takes a song with を. A guitar or piano is not something you sing; you can enjoy its sound with 聞きます. カラオケ is karaoke, and コンサート is a concert.', [
 ['454 を 342~歌います~うたいます','I sing a song.'],['71 と 454 を 342~歌います~うたいます','I sing a song with my friend.'],['331 が 99 です','I like the guitar.'],['331 を 40~聞きます~ききます','I listen to guitar music.'],['334 が 99 です','I like the piano.'],['334 を 40~聞きます~ききます','I listen to piano music.'],['502 で 342~歌います~うたいます','I sing at karaoke.'],['502 が 99 です','I like karaoke.'],['325 は 511 です','The concert is enjoyable.'],['325 で 333 を 40~聞きます~ききます','I listen to music at a concert.']]);
lesson('playing-instruments', 'Playing guitar and piano', [751], 'Instrument + を弾きます', '弾く（ひく） is the playing verb for guitar and piano. Put the instrument before を. The polite forms are 弾きます and 弾きません.', [
 ['1 は 331 を 751~弾きます~ひきます','I play the guitar.'],
 ['71 は 334 を 751~弾きます~ひきます','My friend plays the piano.'],
 ['1 は 334 を 751~弾きません~ひきません','I do not play the piano.'],
 ['51 で 331 を 751~弾きます~ひきます','I play the guitar at home.'],
]);
lesson('sports', 'Sports', [335,337,338,453,595,575,576,45], 'Nをします / Vます', 'Sports such as サッカー and テニス can take をします. 運動します means exercise. 走ります means run; 泳ぎます means swim. The noun スポーツ covers many different sports.', [
 ...lines([[335,'soccer'],[338,'baseball'],[453,'tennis']], [['$ が 99 です','I like $.'],['$ を 45~します~します','I play $.']]),
 ['337 が 99 です','I like sports.'],['337 を 39~見ます~みます','I watch sports.'],['1 は 595~運動します~うんどうします','I exercise.'],['71 と 595~運動します~うんどうします','I exercise with my friend.'],['1 は 575~走ります~はしります','I run.'],['71 と 575~走ります~はしります','I run with my friend.'],['1 は 576~泳ぎます~およぎます','I swim.'],['71 と 576~泳ぎます~およぎます','I swim with my friend.']]);
lesson('quiet-hobbies', 'Quiet interests', [455,458,460,457,459,116], '絵 が 好き です', '読書 is reading as an activity, and 小説 is a novel. 散歩します means take a walk. 遊びます can mean play or spend leisure time together. ダンス is dance.', [
 ['455 が 99 です','I like pictures.'],['455 を 39~見ます~みます','I look at a picture.'],['458 が 99 です','I like novels.'],['458 は 485 です','The novel is interesting.'],['460 が 99 です','I like reading.'],['1 の 336 は 460 です','My hobby is reading.'],['457 が 99 です','I like taking walks.'],['71 と 457~散歩します~さんぽします','I take a walk with my friend.'],['459 が 99 です','I like dance.'],['459 を 39~見ます~みます','I watch dancing.'],['71 と 116~遊びます~あそびます','I spend time with my friend.'],['1 も 116~遊びます~あそびます','I will join in too.']]);
lesson('events', 'Events and photographs', [112,339,341,326,374,623], 'Vませんか / 一緒に', 'The polite negative question Vませんか can be an invitation, not a negative statement. 一緒に means together. 写真を撮る is often shortened to 撮る when the object is clear; these cards practice photographing visible events.', [
 ['339 を 39~見ます~みます','I watch fireworks.'],['339 を 112~撮ります~とります','I photograph fireworks.'],['341 を 112~撮ります~とります','I photograph the festival.'],['341 は 511 です','The festival is enjoyable.'],['326 で 342~歌います~うたいます','I sing at a party.'],['326 は 511 です','The party is enjoyable.'],['374 に 342~歌いません~うたいません か','Would you like to sing together?'],['374 に 576~泳ぎません~およぎません か','Would you like to swim together?'],['623 342~歌って~うたって ください','Please do sing.'],['623 333 を 40~聞いて~きいて ください','Please do listen to the music.']]);
lesson('skills', 'Being good at something', [598,599,461,401,621,381], 'Nが上手です / Nが下手です / どんなN', '上手 and 下手 use が for the skill. Praising another person with 上手 is natural; avoid boasting about yourself with it. どんな comes before a noun and asks what kind. 初めて means for the first time; 一度 means once.', [
 ['71 は 454 が 598 です','My friend is good at singing.'],['4 は 459 が 598 です','The teacher is good at dancing.'],['1 は 454 が 599 です','I am not good at singing.'],['1 は 459 が 599 です','I am not good at dancing.'],['461 333 が 99 です か','What kind of music do you like?'],['461 330 が 99 です か','What kind of movies do you like?'],['333 が 401 99 です','I like music best.'],['453 が 401 99 です','I like tennis best.'],['621 502 で 342~歌います~うたいます','I sing karaoke for the first time.'],['621 339 を 39~見ます~みます','I watch fireworks for the first time.'],['381 454 を 342~歌います~うたいます','I sing the song once.'],['381 333 を 40~聞きます~ききます','I listen to the music once.']]);
